# Generated by Django 3.1.7 on 2021-04-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_images_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='title',
        ),
    ]
