# Generated by Django 3.1.7 on 2021-04-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_images_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bestseller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='trending',
        ),
    ]
