# Generated by Django 3.1.5 on 2021-04-23 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
