# Generated by Django 3.1.7 on 2021-04-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Brands',
        ),
        migrations.RenameField(
            model_name='brands',
            old_name='clients',
            new_name='brands',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='refrences',
        ),
        migrations.AddField(
            model_name='setting',
            name='offer',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
