# Generated by Django 3.1.7 on 2021-04-03 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210403_1244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brands',
        ),
    ]
